import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiEye, FiCheck, FiX } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const GRNList = () => { const [grns, setGrns] = useState([]); const [pos, setPos] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [form, setForm] = useState({ purchaseOrder: '', vendor: '', items: [], vehicleNumber: '', challanNumber: '' });
  useEffect(() => { const fetch = async () => { try { const [g, p] = await Promise.all([api.get('/grn'), api.get('/purchase-orders')]); setGrns(g.data); setPos(p.data.filter(po => po.status === 'approved' || po.status === 'sent')); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, []);
  const handlePOSelect = async (poId) => { const po = pos.find(p => p._id === poId); if (po) { setForm({ ...form, purchaseOrder: poId, vendor: po.vendor?._id || po.vendor, items: (po.items || []).map(i => ({ item: i.item?._id || i.item, description: i.item?.name || i.description, orderedQty: i.quantity, receivedQty: i.quantity, unit: i.unit || 'nos' })) }); } };
  const handleSubmit = async (e) => { e.preventDefault(); try { await api.post('/grn', form); toast.success('GRN Created — Pending IQC'); setShowModal(false); const { data } = await api.get('/grn'); setGrns(data); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  const handleIQC = async (grnId, itemIndex, iqcStatus) => { try { const grn = grns.find(g => g._id === grnId); const item = grn.items[itemIndex]; await api.put(`/grn/${grnId}/iqc`, { itemIndex, iqcStatus, acceptedQty: iqcStatus === 'approved' ? item.receivedQty : 0, rejectedQty: iqcStatus === 'rejected' ? item.receivedQty : 0 }); toast.success(iqcStatus === 'approved' ? 'IQC Approved — Added to Inventory' : 'IQC Rejected'); const { data } = await api.get('/grn'); setGrns(data); } catch { toast.error('Failed'); } };
  const STATUS_COLORS = { pending_iqc: 'bg-amber-900/40 text-amber-400', iqc_in_progress: 'bg-blue-900/40 text-blue-400', partially_accepted: 'bg-purple-900/40 text-purple-400', accepted: 'bg-emerald-900/40 text-emerald-400', rejected: 'bg-red-900/40 text-red-400' };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Goods Received Notes (GRN)</h1><p className="text-sm text-gray-400">Step 6: Receiving & Incoming Quality Check</p></div><button onClick={()=>{setForm({purchaseOrder:'',vendor:'',items:[],vehicleNumber:'',challanNumber:''});setShowModal(true);}} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus />New GRN</button></div>
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-6 py-4 text-gray-400">GRN #</th><th className="text-left px-6 py-4 text-gray-400">PO #</th><th className="text-left px-6 py-4 text-gray-400">Vendor</th><th className="text-left px-6 py-4 text-gray-400">Items</th><th className="text-left px-6 py-4 text-gray-400">Status</th><th className="text-left px-6 py-4 text-gray-400">IQC Actions</th></tr></thead>
      <tbody>{loading ? <tr><td colSpan="6" className="px-6 py-12 text-center text-gray-500">Loading...</td></tr> : grns.map(grn => (<tr key={grn._id} className="border-b border-gray-700/30 hover:bg-gray-800/60"><td className="px-6 py-4 text-emerald-400 font-mono text-xs">{grn.grnNumber}</td><td className="px-6 py-4 text-gray-400 text-xs">{grn.purchaseOrder?.poNumber}</td><td className="px-6 py-4 text-white">{grn.vendor?.name}</td><td className="px-6 py-4 text-gray-300">{grn.items?.length || 0}</td><td className="px-6 py-4"><span className={`px-2.5 py-1 rounded-full text-xs font-medium ${STATUS_COLORS[grn.status]}`}>{grn.status?.replace(/_/g,' ')}</span></td>
        <td className="px-6 py-4">{grn.items?.some(i => i.iqcStatus === 'pending') && (<div className="flex gap-2">{grn.items.map((item, idx) => item.iqcStatus === 'pending' && (<div key={idx} className="flex items-center gap-1"><span className="text-xs text-gray-400">{item.description || `Item ${idx+1}`}:</span><button onClick={() => handleIQC(grn._id, idx, 'approved')} className="p-1 rounded bg-emerald-900/40 text-emerald-400 hover:bg-emerald-900/60" title="Approve"><FiCheck size={12}/></button><button onClick={() => handleIQC(grn._id, idx, 'rejected')} className="p-1 rounded bg-red-900/40 text-red-400 hover:bg-red-900/60" title="Reject"><FiX size={12}/></button></div>))}</div>)}</td></tr>))}</tbody></table></div></div>
    <Modal isOpen={showModal} onClose={()=>setShowModal(false)} title="New GRN"><form onSubmit={handleSubmit} className="space-y-4"><div><label className="block text-sm text-gray-400 mb-1">Purchase Order *</label><select required value={form.purchaseOrder} onChange={e=>handlePOSelect(e.target.value)} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="">Select PO...</option>{pos.map(p=><option key={p._id} value={p._id}>{p.poNumber} — {p.vendor?.name}</option>)}</select></div>
      {form.items.length > 0 && <div><label className="block text-sm text-gray-400 mb-2">Items to Receive</label>{form.items.map((item,idx)=>(<div key={idx} className="flex gap-3 mb-2 bg-gray-900/50 rounded-lg p-3"><span className="text-white text-sm flex-1">{item.description}</span><div className="w-20"><label className="text-xs text-gray-500">Ordered</label><p className="text-gray-400 text-sm">{item.orderedQty}</p></div><div className="w-20"><label className="text-xs text-gray-500">Received</label><input type="number" value={item.receivedQty} onChange={e=>{const upd=[...form.items];upd[idx].receivedQty=Number(e.target.value);setForm({...form,items:upd});}} className="w-full bg-gray-900 border border-gray-700 rounded px-2 py-1 text-white text-sm"/></div></div>))}</div>}
      <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Vehicle No.</label><input value={form.vehicleNumber} onChange={e=>setForm({...form,vehicleNumber:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Challan No.</label><input value={form.challanNumber} onChange={e=>setForm({...form,challanNumber:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div></div>
      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">Create GRN</button></form></Modal></div>);};
export default GRNList;
