import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiEdit2, FiTrash2, FiCheck } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const PurchaseOrders = () => { const [pos, setPos] = useState([]); const [vendors, setVendors] = useState([]); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [form, setForm] = useState({ vendor: '', items: [{ item: '', quantity: 1, unitPrice: 0, taxPercent: 18 }], paymentTerms: 'Net 30', expectedDeliveryDate: '', remarks: '' });
  useEffect(() => { const fetch = async () => { try { const [p, v, i] = await Promise.all([api.get('/purchase-orders'), api.get('/vendors'), api.get('/items')]); setPos(p.data); setVendors(v.data); setItems(i.data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, []);
  const addLineItem = () => setForm({ ...form, items: [...form.items, { item: '', quantity: 1, unitPrice: 0, taxPercent: 18 }] });
  const removeLineItem = (idx) => setForm({ ...form, items: form.items.filter((_, i) => i !== idx) });
  const updateLineItem = (idx, field, value) => { const updated = [...form.items]; updated[idx][field] = value; if (field === 'item') { const sel = items.find(i => i._id === value); if (sel) { updated[idx].unitPrice = sel.costPrice || 0; updated[idx].description = sel.name; } } setForm({ ...form, items: updated }); };
  const handleSubmit = async (e) => { e.preventDefault(); try { const processedItems = form.items.map(i => ({ ...i, totalPrice: i.quantity * i.unitPrice * (1 + (i.taxPercent || 18) / 100), taxAmount: i.quantity * i.unitPrice * ((i.taxPercent || 18) / 100) })); const subtotal = form.items.reduce((s, i) => s + i.quantity * i.unitPrice, 0); const taxAmount = form.items.reduce((s, i) => s + i.quantity * i.unitPrice * ((i.taxPercent || 18) / 100), 0); await api.post('/purchase-orders', { ...form, items: processedItems, subtotal, taxAmount, totalAmount: subtotal + taxAmount }); toast.success('PO Created'); setShowModal(false); const { data } = await api.get('/purchase-orders'); setPos(data); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  const handleApprove = async (id) => { try { await api.put(`/purchase-orders/${id}/approve`); toast.success('Approved'); const { data } = await api.get('/purchase-orders'); setPos(data); } catch { toast.error('Failed'); } };
  const STATUS_COLORS = { draft: 'bg-gray-700 text-gray-300', approved: 'bg-emerald-900/40 text-emerald-400', sent: 'bg-blue-900/40 text-blue-400', partially_received: 'bg-amber-900/40 text-amber-400', received: 'bg-green-900/40 text-green-400', cancelled: 'bg-red-900/40 text-red-400' };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Purchase Orders</h1><p className="text-sm text-gray-400">Step 5: Procurement & material buying</p></div><button onClick={() => { setForm({ vendor: '', items: [{ item: '', quantity: 1, unitPrice: 0, taxPercent: 18 }], paymentTerms: 'Net 30', expectedDeliveryDate: '', remarks: '' }); setShowModal(true); }} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus /> New PO</button></div>
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-6 py-4 text-gray-400">PO #</th><th className="text-left px-6 py-4 text-gray-400">Vendor</th><th className="text-left px-6 py-4 text-gray-400">Items</th><th className="text-left px-6 py-4 text-gray-400">Amount</th><th className="text-left px-6 py-4 text-gray-400">Status</th><th className="text-left px-6 py-4 text-gray-400">Actions</th></tr></thead>
      <tbody>{loading ? <tr><td colSpan="6" className="px-6 py-12 text-center text-gray-500">Loading...</td></tr> : pos.map(po => (<tr key={po._id} className="border-b border-gray-700/30 hover:bg-gray-800/60"><td className="px-6 py-4 text-emerald-400 font-mono text-xs">{po.poNumber}</td><td className="px-6 py-4 text-white">{po.vendor?.name || '—'}<br/><span className="text-xs text-gray-400">{po.vendor?.company}</span></td><td className="px-6 py-4 text-gray-300">{po.items?.length || 0}</td><td className="px-6 py-4 text-white font-semibold">₹{(po.totalAmount || 0).toLocaleString('en-IN')}</td><td className="px-6 py-4"><span className={`px-2.5 py-1 rounded-full text-xs font-medium ${STATUS_COLORS[po.status]}`}>{po.status?.replace(/_/g,' ')}</span></td><td className="px-6 py-4 flex gap-2">{po.status === 'draft' && <button onClick={() => handleApprove(po._id)} className="p-1.5 rounded-lg hover:bg-emerald-900/40 text-gray-400 hover:text-emerald-400" title="Approve"><FiCheck size={14} /></button>}</td></tr>))}</tbody></table></div></div>
    <Modal isOpen={showModal} onClose={() => setShowModal(false)} title="New Purchase Order"><form onSubmit={handleSubmit} className="space-y-4">
      <div><label className="block text-sm text-gray-400 mb-1">Vendor *</label><select required value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="">Select vendor...</option>{vendors.map(v=><option key={v._id} value={v._id}>{v.name} ({v.company})</option>)}</select></div>
      <div><label className="block text-sm text-gray-400 mb-2">Line Items</label>{form.items.map((li, idx) => (<div key={idx} className="flex gap-2 mb-2 items-end"><select value={li.item} onChange={e=>updateLineItem(idx,'item',e.target.value)} className="flex-1 bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:border-emerald-500 focus:outline-none"><option value="">Select item...</option>{items.map(i=><option key={i._id} value={i._id}>{i.itemCode} — {i.name}</option>)}</select><input type="number" min="1" value={li.quantity} onChange={e=>updateLineItem(idx,'quantity',Number(e.target.value))} placeholder="Qty" className="w-20 bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" /><input type="number" value={li.unitPrice} onChange={e=>updateLineItem(idx,'unitPrice',Number(e.target.value))} placeholder="Price" className="w-24 bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" />{form.items.length > 1 && <button type="button" onClick={() => removeLineItem(idx)} className="p-2 text-red-400 hover:bg-red-900/20 rounded-lg"><FiTrash2 size={14} /></button>}</div>))}<button type="button" onClick={addLineItem} className="text-emerald-400 text-sm flex items-center gap-1 hover:text-emerald-300"><FiPlus size={12} /> Add Line</button></div>
      <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Expected Delivery</label><input type="date" value={form.expectedDeliveryDate} onChange={e=>setForm({...form,expectedDeliveryDate:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div><div><label className="block text-sm text-gray-400 mb-1">Payment Terms</label><input value={form.paymentTerms} onChange={e=>setForm({...form,paymentTerms:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div></div>
      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">Create PO</button></form></Modal></div>);};
export default PurchaseOrders;
