import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiEdit2, FiTrash2, FiStar } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const Vendors = () => { const [vendors, setVendors] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [editId, setEditId] = useState(null);
  const [form, setForm] = useState({ name: '', company: '', email: '', phone: '', address: '', city: '', state: '', gst: '', paymentTerms: 'Net 30', leadTimeDays: 7, contactPerson: '', status: 'active' });
  useEffect(() => { const fetch = async () => { try { const { data } = await api.get('/vendors'); setVendors(data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, []);
  const handleSubmit = async (e) => { e.preventDefault(); try { if (editId) { await api.put(`/vendors/${editId}`, form); toast.success('Updated'); } else { await api.post('/vendors', form); toast.success('Created'); } setShowModal(false); setEditId(null); const { data } = await api.get('/vendors'); setVendors(data); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  const handleEdit = (v) => { setForm({ name: v.name, company: v.company, email: v.email||'', phone: v.phone||'', address: v.address||'', city: v.city||'', state: v.state||'', gst: v.gst||'', paymentTerms: v.paymentTerms||'', leadTimeDays: v.leadTimeDays||7, contactPerson: v.contactPerson||'', status: v.status }); setEditId(v._id); setShowModal(true); };
  const handleDelete = async (id) => { if(!window.confirm('Delete?')) return; try { await api.delete(`/vendors/${id}`); toast.success('Deleted'); const{data}=await api.get('/vendors'); setVendors(data); } catch{toast.error('Failed');} };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Vendors / Suppliers</h1><p className="text-sm text-gray-400">Manage your material suppliers</p></div><button onClick={()=>{setEditId(null);setForm({name:'',company:'',email:'',phone:'',address:'',city:'',state:'',gst:'',paymentTerms:'Net 30',leadTimeDays:7,contactPerson:'',status:'active'});setShowModal(true);}} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus />New Vendor</button></div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{loading ? <p className="text-gray-500 col-span-3 text-center py-12">Loading...</p> : vendors.map(v=>(<div key={v._id} className="bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5 hover:border-gray-600/50 transition-all"><div className="flex justify-between items-start mb-3"><div><h3 className="text-white font-semibold">{v.name}</h3><p className="text-sm text-gray-400">{v.company}</p></div><span className={`px-2 py-0.5 rounded-full text-xs ${v.status==='active'?'bg-emerald-900/40 text-emerald-400':v.status==='blacklisted'?'bg-red-900/40 text-red-400':'bg-gray-700 text-gray-400'}`}>{v.status}</span></div>
      <div className="space-y-1 text-sm text-gray-400 mb-3">{v.phone&&<p>📞 {v.phone}</p>}{v.email&&<p>✉️ {v.email}</p>}{v.city&&<p>📍 {v.city}, {v.state}</p>}{v.gst&&<p className="font-mono text-xs">GST: {v.gst}</p>}</div>
      <div className="flex items-center justify-between"><div className="flex">{[1,2,3,4,5].map(s=>(<FiStar key={s} size={14} className={s<=v.rating?'text-amber-400 fill-amber-400':'text-gray-600'} />))}</div><div className="flex gap-2"><button onClick={()=>handleEdit(v)} className="p-1.5 rounded-lg hover:bg-gray-700 text-gray-400 hover:text-white"><FiEdit2 size={14}/></button><button onClick={()=>handleDelete(v._id)} className="p-1.5 rounded-lg hover:bg-red-900/40 text-gray-400 hover:text-red-400"><FiTrash2 size={14}/></button></div></div></div>))}</div>
    <Modal isOpen={showModal} onClose={()=>setShowModal(false)} title={editId?'Edit Vendor':'New Vendor'}><form onSubmit={handleSubmit} className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Name *</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Company *</label><input required value={form.company} onChange={e=>setForm({...form,company:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Email</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Phone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">GST</label><input value={form.gst} onChange={e=>setForm({...form,gst:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Contact Person</label><input value={form.contactPerson} onChange={e=>setForm({...form,contactPerson:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div></div><div><label className="block text-sm text-gray-400 mb-1">Address</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">{editId?'Update':'Create'} Vendor</button></form></Modal></div>);};
export default Vendors;
