import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiTruck, FiCheck, FiPackage } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const DespatchList = () => { const [despatches, setDespatches] = useState([]); const [saleOrders, setSaleOrders] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({ saleOrder: '', client: '', deliveryAddress: '', transporterName: '', vehicleNumber: '', driverName: '', driverPhone: '', ewayBillNumber: '', totalPackages: 1 });
  useEffect(() => { const fetch = async () => { try { const [d, s] = await Promise.all([api.get('/despatch'), api.get('/sale-orders')]); setDespatches(d.data); setSaleOrders(s.data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, []);
  const handleSOSelect = (soId) => { const so = saleOrders.find(s => s._id === soId); if (so) setForm({ ...form, saleOrder: soId, client: so.client?._id || so.client }); };
  const handleSubmit = async (e) => { e.preventDefault(); try { await api.post('/despatch', form); toast.success('Despatch Created'); setShowModal(false); const { data } = await api.get('/despatch'); setDespatches(data); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  const handleStatusUpdate = async (id, status) => { try { await api.put(`/despatch/${id}`, { status }); toast.success(`Status → ${status}`); const { data } = await api.get('/despatch'); setDespatches(data); } catch { toast.error('Failed'); } };
  const STATUS_COLORS = { packing: 'bg-amber-900/40 text-amber-400', ready: 'bg-blue-900/40 text-blue-400', despatched: 'bg-indigo-900/40 text-indigo-400', in_transit: 'bg-purple-900/40 text-purple-400', delivered: 'bg-emerald-900/40 text-emerald-400' };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Despatch</h1><p className="text-sm text-gray-400">Step 9: Packing, shipping & delivery</p></div><button onClick={()=>{setForm({saleOrder:'',client:'',deliveryAddress:'',transporterName:'',vehicleNumber:'',driverName:'',driverPhone:'',ewayBillNumber:'',totalPackages:1});setShowModal(true);}} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus />New Despatch</button></div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{loading ? <p className="text-gray-500 col-span-3 text-center py-12">Loading...</p> : despatches.map(d=>(<div key={d._id} className="bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5"><div className="flex justify-between items-start mb-3"><div><p className="text-emerald-400 font-mono text-xs">{d.despatchNumber}</p><p className="text-white font-semibold mt-1">{d.client?.name || '—'}</p><p className="text-xs text-gray-400">SO: {d.saleOrder?.soNumber}</p></div><span className={`px-2.5 py-1 rounded-full text-xs font-medium ${STATUS_COLORS[d.status]}`}>{d.status?.replace(/_/g,' ')}</span></div>
      {d.vehicleNumber && <p className="text-sm text-gray-400 mb-1"><FiTruck className="inline mr-1" size={14}/>Vehicle: {d.vehicleNumber}</p>}
      {d.ewayBillNumber && <p className="text-xs text-gray-400 mb-3">E-Way: {d.ewayBillNumber}</p>}
      <div className="flex gap-2 mt-3">{d.status==='packing' && <button onClick={()=>handleStatusUpdate(d._id,'ready')} className="px-3 py-1.5 bg-blue-600/20 text-blue-400 rounded-lg text-xs hover:bg-blue-600/30">Mark Ready</button>}
      {d.status==='ready' && <button onClick={()=>handleStatusUpdate(d._id,'despatched')} className="px-3 py-1.5 bg-indigo-600/20 text-indigo-400 rounded-lg text-xs hover:bg-indigo-600/30"><FiTruck className="inline mr-1" size={12}/>Despatch</button>}
      {d.status==='despatched' && <button onClick={()=>handleStatusUpdate(d._id,'delivered')} className="px-3 py-1.5 bg-emerald-600/20 text-emerald-400 rounded-lg text-xs hover:bg-emerald-600/30"><FiCheck className="inline mr-1" size={12}/>Delivered</button>}</div></div>))}</div>
    <Modal isOpen={showModal} onClose={()=>setShowModal(false)} title="New Despatch"><form onSubmit={handleSubmit} className="space-y-4">
      <div><label className="block text-sm text-gray-400 mb-1">Sale Order *</label><select required value={form.saleOrder} onChange={e=>handleSOSelect(e.target.value)} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="">Select...</option>{saleOrders.filter(s=>['ready_for_despatch','quality_check'].includes(s.status)).map(s=><option key={s._id} value={s._id}>{s.soNumber} — {s.subject}</option>)}</select></div>
      <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Transporter Name</label><input value={form.transporterName} onChange={e=>setForm({...form,transporterName:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Vehicle Number</label><input value={form.vehicleNumber} onChange={e=>setForm({...form,vehicleNumber:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">E-Way Bill</label><input value={form.ewayBillNumber} onChange={e=>setForm({...form,ewayBillNumber:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Total Packages</label><input type="number" value={form.totalPackages} onChange={e=>setForm({...form,totalPackages:Number(e.target.value)})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div></div>
      <div><label className="block text-sm text-gray-400 mb-1">Delivery Address</label><textarea rows="2" value={form.deliveryAddress} onChange={e=>setForm({...form,deliveryAddress:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"></textarea></div>
      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">Create Despatch</button></form></Modal></div>);};
export default DespatchList;
