import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiCheck, FiX, FiEye } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const IQCInspections = () => { const [inspections, setInspections] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({ inspectionType: 'iqc', referenceType: 'grn', referenceId: '', productName: '', quantity: 0, sampleSize: 0, parameters: [{ parameter: '', specification: '', actualValue: '', result: 'na' }] });
  const [grns, setGrns] = useState([]);
  useEffect(() => { const fetchLocal = async () => { try { const [{ data: insp }, { data: grnData }] = await Promise.all([api.get('/quality', { params: { inspectionType: 'iqc' } }), api.get('/grn')]); setInspections(insp); setGrns(grnData.filter(g => g.status === 'pending_iqc' || g.status === 'iqc_in_progress')); } catch { toast.error('Failed to load data'); } finally { setLoading(false); } }; fetchLocal(); }, []);
  const addParam = () => setForm({ ...form, parameters: [...form.parameters, { parameter: '', specification: '', actualValue: '', result: 'na' }] });
  const updateParam = (idx, field, val) => { const params = [...form.parameters]; params[idx][field] = val; setForm({ ...form, parameters: params }); };
  const handleSubmit = async (e) => { e.preventDefault(); try { await api.post('/quality', form); toast.success('IQC Created'); setShowModal(false); const { data } = await api.get('/quality', { params: { inspectionType: 'iqc' } }); setInspections(data); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  const handleResult = async (id, result) => { try { await api.put(`/quality/${id}/result`, { overallResult: result }); toast.success(result === 'accepted' ? 'Accepted' : 'Rejected'); const { data } = await api.get('/quality', { params: { inspectionType: 'iqc' } }); setInspections(data); } catch { toast.error('Failed'); } };
  const RESULT_COLORS = { pending: 'bg-amber-900/40 text-amber-400', accepted: 'bg-emerald-900/40 text-emerald-400', rejected: 'bg-red-900/40 text-red-400', conditional_accept: 'bg-purple-900/40 text-purple-400' };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">IQC — Incoming Quality Control</h1><p className="text-sm text-gray-400">Step 6b: Inspect incoming materials</p></div><button onClick={()=>{setForm({inspectionType:'iqc',referenceType:'grn',referenceId:'',productName:'',quantity:0,sampleSize:0,parameters:[{parameter:'',specification:'',actualValue:'',result:'na'}]});setShowModal(true);}} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus />New IQC</button></div>
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-6 py-4 text-gray-400">Inspection #</th><th className="text-left px-6 py-4 text-gray-400">Item</th><th className="text-left px-6 py-4 text-gray-400">GRN</th><th className="text-left px-6 py-4 text-gray-400">Qty / Sample</th><th className="text-left px-6 py-4 text-gray-400">Result</th><th className="text-left px-6 py-4 text-gray-400">Actions</th></tr></thead>
      <tbody>{loading ? <tr><td colSpan="6" className="px-6 py-12 text-center text-gray-500">Loading...</td></tr> : inspections.map(insp=>(<tr key={insp._id} className="border-b border-gray-700/30 hover:bg-gray-800/60"><td className="px-6 py-4 text-emerald-400 font-mono text-xs">{insp.inspectionNumber}</td><td className="px-6 py-4 text-white">{insp.item?.name || insp.productName}</td><td className="px-6 py-4 text-gray-400 text-xs">{insp.grn?.grnNumber || '—'}</td><td className="px-6 py-4 text-gray-300">{insp.quantity} / {insp.sampleSize}</td><td className="px-6 py-4"><span className={`px-2.5 py-1 rounded-full text-xs font-medium ${RESULT_COLORS[insp.overallResult]}`}>{insp.overallResult?.replace(/_/g,' ')}</span></td>
        <td className="px-6 py-4">{insp.overallResult==='pending' && (<div className="flex gap-2"><button onClick={()=>handleResult(insp._id,'accepted')} className="p-1.5 rounded-lg bg-emerald-900/40 text-emerald-400 hover:bg-emerald-900/60" title="Accept"><FiCheck size={14}/></button><button onClick={()=>handleResult(insp._id,'rejected')} className="p-1.5 rounded-lg bg-red-900/40 text-red-400 hover:bg-red-900/60" title="Reject"><FiX size={14}/></button></div>)}</td></tr>))}</tbody></table></div></div>
    <Modal isOpen={showModal} onClose={()=>setShowModal(false)} title="New IQC Inspection"><form onSubmit={handleSubmit} className="space-y-4">
      <div><label className="block text-sm text-gray-400 mb-1">Select GRN (Pending IQC) *</label><select required value={form.referenceId} onChange={e=>setForm({...form, referenceId: e.target.value, grn: e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="">Select GRN...</option>{grns.map(g=><option key={g._id} value={g._id}>{g.grnNumber} — {g.vendor?.name}</option>)}</select></div>
      <div><label className="block text-sm text-gray-400 mb-1">Product/Material Name *</label><input required value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div>
      <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Quantity</label><input type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Sample Size</label><input type="number" value={form.sampleSize} onChange={e=>setForm({...form,sampleSize:Number(e.target.value)})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div></div>
      <div><label className="block text-sm text-gray-400 mb-2">Inspection Parameters</label>{form.parameters.map((p,idx)=>(<div key={idx} className="grid grid-cols-4 gap-2 mb-2"><input value={p.parameter} onChange={e=>updateParam(idx,'parameter',e.target.value)} placeholder="Parameter" className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none"/><input value={p.specification} onChange={e=>updateParam(idx,'specification',e.target.value)} placeholder="Spec" className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none"/><input value={p.actualValue} onChange={e=>updateParam(idx,'actualValue',e.target.value)} placeholder="Actual" className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none"/><select value={p.result} onChange={e=>updateParam(idx,'result',e.target.value)} className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none"><option value="na">N/A</option><option value="pass">Pass</option><option value="fail">Fail</option></select></div>))}<button type="button" onClick={addParam} className="text-emerald-400 text-sm"><FiPlus className="inline mr-1" size={12}/>Add Parameter</button></div>
      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">Create IQC Inspection</button></form></Modal></div>);};
export default IQCInspections;
