import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiEdit2, FiSearch, FiTool } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const ServiceList = () => { const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [search, setSearch] = useState('');
  const [form, setForm] = useState({ productName: '', serialNumber: '', serviceType: 'installation', reportedIssue: '', installationDate: '', client: '' });
  useEffect(() => { const fetch = async () => { try { const { data } = await api.get('/service'); setRecords(data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, []);
  const handleSubmit = async (e) => { e.preventDefault(); try { await api.post('/service', form); toast.success('Service Record Created'); setShowModal(false); const { data } = await api.get('/service'); setRecords(data); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  const handleLookup = async () => { if (!search) return; try { const { data } = await api.get(`/service/serial/${search}`); toast.success(`Found ${data.serviceHistory.length} records`); setRecords(data.serviceHistory); } catch { toast.error('Not found'); } };
  const TYPE_COLORS = { installation: 'bg-blue-900/40 text-blue-400', preventive_maintenance: 'bg-teal-900/40 text-teal-400', breakdown: 'bg-red-900/40 text-red-400', warranty_repair: 'bg-amber-900/40 text-amber-400', paid_service: 'bg-purple-900/40 text-purple-400', annual_maintenance: 'bg-indigo-900/40 text-indigo-400' };
  const STATUS_COLORS = { scheduled: 'bg-blue-900/40 text-blue-400', in_progress: 'bg-amber-900/40 text-amber-400', completed: 'bg-emerald-900/40 text-emerald-400', pending_parts: 'bg-purple-900/40 text-purple-400' };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Installation & Service</h1><p className="text-sm text-gray-400">Step 10: After-sales support & warranty</p></div><button onClick={()=>{setForm({productName:'',serialNumber:'',serviceType:'installation',reportedIssue:'',installationDate:'',client:''});setShowModal(true);}} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus />New Record</button></div>
    <div className="flex gap-2"><div className="relative flex-1"><FiSearch className="absolute left-4 top-3 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Lookup by Serial Number..." className="w-full bg-gray-800/50 border border-gray-700/50 rounded-xl pl-10 pr-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><button onClick={handleLookup} className="px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-medium">Lookup</button></div>
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-6 py-4 text-gray-400">Service #</th><th className="text-left px-6 py-4 text-gray-400">Product</th><th className="text-left px-6 py-4 text-gray-400">Serial #</th><th className="text-left px-6 py-4 text-gray-400">Type</th><th className="text-left px-6 py-4 text-gray-400">Client</th><th className="text-left px-6 py-4 text-gray-400">Status</th><th className="text-left px-6 py-4 text-gray-400">Date</th></tr></thead>
      <tbody>{loading ? <tr><td colSpan="7" className="px-6 py-12 text-center text-gray-500">Loading...</td></tr> : records.map(r=>(<tr key={r._id} className="border-b border-gray-700/30 hover:bg-gray-800/60"><td className="px-6 py-4 text-emerald-400 font-mono text-xs">{r.serviceNumber}</td><td className="px-6 py-4 text-white">{r.productName}</td><td className="px-6 py-4 text-gray-300 font-mono text-xs">{r.serialNumber}</td><td className="px-6 py-4"><span className={`px-2 py-0.5 rounded-full text-xs ${TYPE_COLORS[r.serviceType]}`}>{r.serviceType?.replace(/_/g,' ')}</span></td><td className="px-6 py-4 text-gray-400">{r.client?.name || '—'}</td><td className="px-6 py-4"><span className={`px-2 py-0.5 rounded-full text-xs ${STATUS_COLORS[r.status]}`}>{r.status?.replace(/_/g,' ')}</span></td><td className="px-6 py-4 text-gray-400 text-xs">{new Date(r.createdAt).toLocaleDateString('en-IN')}</td></tr>))}</tbody></table></div></div>
    <Modal isOpen={showModal} onClose={()=>setShowModal(false)} title="New Service Record"><form onSubmit={handleSubmit} className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Product Name *</label><input required value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Serial Number *</label><input required value={form.serialNumber} onChange={e=>setForm({...form,serialNumber:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div></div>
      <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Service Type *</label><select value={form.serviceType} onChange={e=>setForm({...form,serviceType:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="installation">Installation</option><option value="preventive_maintenance">Preventive Maintenance</option><option value="breakdown">Breakdown</option><option value="warranty_repair">Warranty Repair</option><option value="paid_service">Paid Service</option><option value="annual_maintenance">Annual Maintenance</option></select></div>{form.serviceType==='installation' && <div><label className="block text-sm text-gray-400 mb-1">Installation Date</label><input type="date" value={form.installationDate} onChange={e=>setForm({...form,installationDate:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div>}</div>
      <div><label className="block text-sm text-gray-400 mb-1">Reported Issue</label><textarea rows="3" value={form.reportedIssue} onChange={e=>setForm({...form,reportedIssue:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"></textarea></div>
      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">Create Service Record</button></form></Modal></div>);};
export default ServiceList;
