import { useState, useEffect } from 'react';import { useParams, useNavigate } from 'react-router-dom';import api from '../../services/api';import toast from 'react-hot-toast';import { FiArrowLeft, FiPlus, FiTrash2, FiCheck, FiAlertTriangle } from 'react-icons/fi';
const BOMDetail = () => { const { id } = useParams(); const navigate = useNavigate(); const [bom, setBom] = useState(null); const [loading, setLoading] = useState(true); const [items, setItems] = useState([]); const [newItem, setNewItem] = useState({ item: '', quantity: 1, unit: 'nos', itemType: 'raw_material', remarks: '' });
  useEffect(() => { const fetch = async () => { try { const [b, i] = await Promise.all([api.get(`/bom/${id}`), api.get('/items')]); setBom(b.data); setItems(i.data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, [id]);
  const addBOMItem = async () => { if (!newItem.item) return toast.error('Select an item'); try { const selectedItem = items.find(i => i._id === newItem.item); const updatedItems = [...(bom.items || []), { ...newItem, description: selectedItem?.name, costPerUnit: selectedItem?.costPrice || 0, totalCost: (selectedItem?.costPrice || 0) * newItem.quantity }]; const totalMaterialCost = updatedItems.reduce((s, i) => s + (i.totalCost || 0), 0); await api.put(`/bom/${id}`, { items: updatedItems, totalMaterialCost }); const { data } = await api.get(`/bom/${id}`); setBom(data); setNewItem({ item: '', quantity: 1, unit: 'nos', itemType: 'raw_material', remarks: '' }); toast.success('Item added'); } catch { toast.error('Failed'); } };
  const removeBOMItem = async (idx) => { const updatedItems = bom.items.filter((_, i) => i !== idx); const totalMaterialCost = updatedItems.reduce((s, i) => s + (i.totalCost || 0), 0); try { await api.put(`/bom/${id}`, { items: updatedItems, totalMaterialCost }); const { data } = await api.get(`/bom/${id}`); setBom(data); toast.success('Removed'); } catch { toast.error('Failed'); } };
  if (loading) return <div className="flex justify-center py-20"><div className="animate-spin rounded-full h-12 w-12 border-t-2 border-emerald-500"></div></div>;
  if (!bom) return <p className="text-gray-400 text-center py-20">BOM not found</p>;
  return (<div className="space-y-6"><div className="flex items-center gap-4"><button onClick={() => navigate('/bom')} className="p-2 rounded-lg hover:bg-gray-800 text-gray-400"><FiArrowLeft /></button><div><h1 className="text-2xl font-bold text-white">{bom.bomNumber}</h1><p className="text-sm text-gray-400">{bom.productName} — SO: {bom.saleOrder?.soNumber}</p></div><span className={`ml-auto px-3 py-1 rounded-full text-xs font-medium ${bom.status === 'approved' ? 'bg-emerald-900/40 text-emerald-400' : 'bg-amber-900/40 text-amber-400'}`}>{bom.status}</span></div>
    {/* BOM Items */}
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6"><h3 className="text-lg font-semibold text-white mb-4">Material List ({bom.items?.length || 0} items)</h3>
      <table className="w-full text-sm mb-4"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-4 py-3 text-gray-400">Item</th><th className="text-left px-4 py-3 text-gray-400">Type</th><th className="text-left px-4 py-3 text-gray-400">Qty</th><th className="text-left px-4 py-3 text-gray-400">Unit</th><th className="text-left px-4 py-3 text-gray-400">Cost/Unit</th><th className="text-left px-4 py-3 text-gray-400">Total</th><th className="px-4 py-3"></th></tr></thead>
        <tbody>{(bom.items || []).map((item, idx) => (<tr key={idx} className="border-b border-gray-700/30"><td className="px-4 py-3 text-white">{item.item?.name || item.description}</td><td className="px-4 py-3"><span className="px-2 py-0.5 bg-gray-700 rounded-full text-xs text-gray-300">{item.itemType}</span></td><td className="px-4 py-3 text-gray-300">{item.quantity}</td><td className="px-4 py-3 text-gray-400">{item.unit}</td><td className="px-4 py-3 text-gray-300">₹{(item.costPerUnit || 0).toLocaleString('en-IN')}</td><td className="px-4 py-3 text-emerald-400 font-medium">₹{(item.totalCost || 0).toLocaleString('en-IN')}</td><td className="px-4 py-3">{bom.status === 'draft' && <button onClick={() => removeBOMItem(idx)} className="p-1 rounded hover:bg-red-900/40 text-gray-400 hover:text-red-400"><FiTrash2 size={12} /></button>}</td></tr>))}</tbody>
        <tfoot><tr className="border-t border-gray-600"><td colSpan="5" className="px-4 py-3 text-white font-semibold text-right">Total Material Cost</td><td className="px-4 py-3 text-emerald-400 font-bold text-lg">₹{(bom.totalMaterialCost || 0).toLocaleString('en-IN')}</td><td></td></tr></tfoot></table>
      {bom.status === 'draft' && (<div className="flex gap-3 items-end border-t border-gray-700/50 pt-4">
        <div className="flex-1"><label className="block text-xs text-gray-400 mb-1">Item</label><select value={newItem.item} onChange={e=>setNewItem({...newItem,item:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:border-emerald-500 focus:outline-none"><option value="">Select item...</option>{items.map(i=><option key={i._id} value={i._id}>{i.itemCode} — {i.name}</option>)}</select></div>
        <div className="w-20"><label className="block text-xs text-gray-400 mb-1">Qty</label><input type="number" min="1" value={newItem.quantity} onChange={e=>setNewItem({...newItem,quantity:Number(e.target.value)})} className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:border-emerald-500 focus:outline-none" /></div>
        <div className="w-24"><label className="block text-xs text-gray-400 mb-1">Type</label><select value={newItem.itemType} onChange={e=>setNewItem({...newItem,itemType:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:border-emerald-500 focus:outline-none"><option value="raw_material">Raw</option><option value="bought_out">Bought Out</option><option value="sub_assembly">Sub-Assy</option><option value="consumable">Consumable</option></select></div>
        <button onClick={addBOMItem} className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-sm font-medium flex items-center gap-1"><FiPlus size={14} /> Add</button></div>)}</div>
    {/* Shortage Check Results */}
    {bom.shortageChecked && bom.shortageItems?.length > 0 && (<div className="bg-red-900/20 border border-red-700/50 rounded-2xl p-6"><h3 className="text-lg font-semibold text-red-400 mb-3 flex items-center gap-2"><FiAlertTriangle /> Material Shortage</h3>
      <div className="space-y-2">{bom.shortageItems.map((s, i) => (<div key={i} className="flex justify-between bg-red-900/20 rounded-xl px-4 py-3 text-sm"><span className="text-white">{s.item?.name || s.item?.itemCode}</span><span className="text-red-400">Required: {s.required} | Available: {s.available} | Short: {s.shortage}</span></div>))}</div></div>)}</div>);};
export default BOMDetail;
