import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiEye, FiTrash2, FiCheck, FiAlertTriangle } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const BOMList = () => { const [boms, setBoms] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [saleOrders, setSaleOrders] = useState([]); const [form, setForm] = useState({ saleOrder: '', productName: '', designNotes: '', items: [], operations: [] }); const navigate = useNavigate();
  useEffect(() => { const fetch = async () => { try { const [b, s] = await Promise.all([api.get('/bom'), api.get('/sale-orders')]); setBoms(b.data); setSaleOrders(s.data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, []);
  const handleSubmit = async (e) => { e.preventDefault(); try { await api.post('/bom', form); toast.success('BOM Created'); setShowModal(false); const { data } = await api.get('/bom'); setBoms(data); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  const handleApprove = async (id) => { try { await api.put(`/bom/${id}/approve`); toast.success('Approved'); const { data } = await api.get('/bom'); setBoms(data); } catch { toast.error('Failed'); } };
  const handleShortageCheck = async (id) => { try { const { data } = await api.get(`/bom/${id}/shortage`); if (data.allAvailable) toast.success('All materials available!'); else toast(`${data.shortageCount} items short`, { icon: '⚠️' }); } catch { toast.error('Failed'); } };
  const STATUS_COLORS = { draft: 'bg-gray-700 text-gray-300', in_review: 'bg-amber-900/40 text-amber-400', approved: 'bg-emerald-900/40 text-emerald-400', released: 'bg-blue-900/40 text-blue-400', obsolete: 'bg-red-900/40 text-red-400' };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Bill of Materials</h1><p className="text-sm text-gray-400">Step 4: Design & BOM creation</p></div><button onClick={() => setShowModal(true)} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus /> New BOM</button></div>
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-6 py-4 text-gray-400 font-medium">BOM #</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Product</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Sale Order</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Items</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Status</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Actions</th></tr></thead>
      <tbody>{loading ? <tr><td colSpan="6" className="px-6 py-12 text-center text-gray-500">Loading...</td></tr> : boms.length === 0 ? <tr><td colSpan="6" className="px-6 py-12 text-center text-gray-500">No BOMs</td></tr> : boms.map(b => (
        <tr key={b._id} className="border-b border-gray-700/30 hover:bg-gray-800/60"><td className="px-6 py-4 text-emerald-400 font-mono text-xs">{b.bomNumber}</td><td className="px-6 py-4 text-white">{b.productName}</td><td className="px-6 py-4 text-gray-400 text-xs">{b.saleOrder?.soNumber || '—'}</td><td className="px-6 py-4 text-gray-300">{b.items?.length || 0}</td><td className="px-6 py-4"><span className={`px-2.5 py-1 rounded-full text-xs font-medium ${STATUS_COLORS[b.status]}`}>{b.status}</span></td>
        <td className="px-6 py-4"><div className="flex gap-2"><button onClick={() => navigate(`/bom/${b._id}`)} className="p-1.5 rounded-lg hover:bg-gray-700 text-gray-400 hover:text-white"><FiEye size={14} /></button>{b.status === 'draft' && <button onClick={() => handleApprove(b._id)} className="p-1.5 rounded-lg hover:bg-emerald-900/40 text-gray-400 hover:text-emerald-400" title="Approve"><FiCheck size={14} /></button>}{b.status === 'approved' && <button onClick={() => handleShortageCheck(b._id)} className="p-1.5 rounded-lg hover:bg-amber-900/40 text-gray-400 hover:text-amber-400" title="Check Shortage"><FiAlertTriangle size={14} /></button>}</div></td></tr>))}</tbody></table></div></div>
    <Modal isOpen={showModal} onClose={() => setShowModal(false)} title="New BOM"><form onSubmit={handleSubmit} className="space-y-4">
      <div><label className="block text-sm text-gray-400 mb-1">Sale Order *</label><select required value={form.saleOrder} onChange={e=>setForm({...form,saleOrder:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="">Select...</option>{saleOrders.filter(s=>s.status==='confirmed'||s.status==='design_pending').map(s=><option key={s._id} value={s._id}>{s.soNumber} — {s.subject}</option>)}</select></div>
      <div><label className="block text-sm text-gray-400 mb-1">Product Name *</label><input required value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
      <div><label className="block text-sm text-gray-400 mb-1">Design Notes</label><textarea rows="3" value={form.designNotes} onChange={e=>setForm({...form,designNotes:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"></textarea></div>
      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">Create BOM</button></form></Modal></div>);};
export default BOMList;
