import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiEdit2, FiTrash2, FiEye } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const TYPE_LABELS = { raw_material: 'Raw Material', finished_good: 'Finished Good', semi_finished: 'Semi-Finished', consumable: 'Consumable', spare_part: 'Spare Part', bought_out: 'Bought Out' };
const ItemMaster = () => {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [editId, setEditId] = useState(null); const [filter, setFilter] = useState('');
  const [form, setForm] = useState({ name: '', type: 'raw_material', category: '', unit: 'nos', description: '', hsnCode: '', reorderLevel: 0, reorderQty: 0, leadTimeDays: 0, costPrice: 0, sellingPrice: 0, taxPercent: 18 });
  const fetchItems = async () => { try { const params = {}; if (filter) params.type = filter; const { data } = await api.get('/items', { params }); setItems(data); } catch { toast.error('Failed'); } finally { setLoading(false); } };
  useEffect(() => { fetchItems(); }, [filter]);
  const handleSubmit = async (e) => { e.preventDefault(); try { if (editId) { await api.put(`/items/${editId}`, form); toast.success('Updated'); } else { await api.post('/items', form); toast.success('Created'); } setShowModal(false); setEditId(null); fetchItems(); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  const handleEdit = (item) => { setForm({ name: item.name, type: item.type, category: item.category || '', unit: item.unit, description: item.description || '', hsnCode: item.hsnCode || '', reorderLevel: item.reorderLevel || 0, reorderQty: item.reorderQty || 0, leadTimeDays: item.leadTimeDays || 0, costPrice: item.costPrice || 0, sellingPrice: item.sellingPrice || 0, taxPercent: item.taxPercent || 18 }); setEditId(item._id); setShowModal(true); };
  const handleDelete = async (id) => { if (!window.confirm('Delete?')) return; try { await api.delete(`/items/${id}`); toast.success('Deleted'); fetchItems(); } catch { toast.error('Failed'); } };
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div><h1 className="text-2xl font-bold text-white">Item Master</h1><p className="text-sm text-gray-400">Raw materials, finished goods & components</p></div>
        <button onClick={() => { setEditId(null); setForm({ name: '', type: 'raw_material', category: '', unit: 'nos', description: '', hsnCode: '', reorderLevel: 0, reorderQty: 0, leadTimeDays: 0, costPrice: 0, sellingPrice: 0, taxPercent: 18 }); setShowModal(true); }} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium transition-colors"><FiPlus /> New Item</button>
      </div>
      <div className="flex flex-wrap gap-2">{['', 'raw_material', 'finished_good', 'semi_finished', 'bought_out', 'consumable', 'spare_part'].map(t => (<button key={t} onClick={() => setFilter(t)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${filter === t ? 'bg-emerald-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}>{t ? TYPE_LABELS[t] : 'All'}</button>))}</div>
      <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-6 py-4 text-gray-400 font-medium">Code</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Name</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Type</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Unit</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Cost</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Stock Level</th><th className="text-left px-6 py-4 text-gray-400 font-medium">Actions</th></tr></thead>
        <tbody>{loading ? <tr><td colSpan="7" className="px-6 py-12 text-center text-gray-500">Loading...</td></tr> : items.length === 0 ? <tr><td colSpan="7" className="px-6 py-12 text-center text-gray-500">No items</td></tr> : items.map(item => (
          <tr key={item._id} className="border-b border-gray-700/30 hover:bg-gray-800/60">
            <td className="px-6 py-4 text-emerald-400 font-mono text-xs">{item.itemCode}</td>
            <td className="px-6 py-4"><p className="text-white font-medium">{item.name}</p><p className="text-xs text-gray-400">{item.category}</p></td>
            <td className="px-6 py-4"><span className="px-2 py-0.5 bg-gray-700 text-gray-300 rounded-full text-xs">{TYPE_LABELS[item.type]}</span></td>
            <td className="px-6 py-4 text-gray-300">{item.unit}</td>
            <td className="px-6 py-4 text-white">₹{(item.costPrice || 0).toLocaleString('en-IN')}</td>
            <td className="px-6 py-4 text-gray-400">{item.reorderLevel > 0 ? `ROL: ${item.reorderLevel}` : '—'}</td>
            <td className="px-6 py-4 flex gap-2"><button onClick={() => handleEdit(item)} className="p-1.5 rounded-lg hover:bg-gray-700 text-gray-400 hover:text-white"><FiEdit2 size={14} /></button><button onClick={() => handleDelete(item._id)} className="p-1.5 rounded-lg hover:bg-red-900/40 text-gray-400 hover:text-red-400"><FiTrash2 size={14} /></button></td>
          </tr>))}</tbody></table></div></div>
      <Modal isOpen={showModal} onClose={() => setShowModal(false)} title={editId ? 'Edit Item' : 'New Item'}>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div><label className="block text-sm text-gray-400 mb-1">Name *</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
            <div><label className="block text-sm text-gray-400 mb-1">Type *</label><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none">{Object.entries(TYPE_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
            <div><label className="block text-sm text-gray-400 mb-1">Category</label><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
            <div><label className="block text-sm text-gray-400 mb-1">Unit *</label><select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none">{['nos','kg','gm','liters','meters','sqm','set','pair','box'].map(u=><option key={u} value={u}>{u}</option>)}</select></div>
            <div><label className="block text-sm text-gray-400 mb-1">Cost Price (₹)</label><input type="number" value={form.costPrice} onChange={e=>setForm({...form,costPrice:Number(e.target.value)})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
            <div><label className="block text-sm text-gray-400 mb-1">Selling Price (₹)</label><input type="number" value={form.sellingPrice} onChange={e=>setForm({...form,sellingPrice:Number(e.target.value)})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
            <div><label className="block text-sm text-gray-400 mb-1">HSN Code</label><input value={form.hsnCode} onChange={e=>setForm({...form,hsnCode:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
            <div><label className="block text-sm text-gray-400 mb-1">Tax %</label><input type="number" value={form.taxPercent} onChange={e=>setForm({...form,taxPercent:Number(e.target.value)})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
            <div><label className="block text-sm text-gray-400 mb-1">Reorder Level</label><input type="number" value={form.reorderLevel} onChange={e=>setForm({...form,reorderLevel:Number(e.target.value)})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
            <div><label className="block text-sm text-gray-400 mb-1">Lead Time (days)</label><input type="number" value={form.leadTimeDays} onChange={e=>setForm({...form,leadTimeDays:Number(e.target.value)})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
          </div>
          <div><label className="block text-sm text-gray-400 mb-1">Description</label><textarea rows="2" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"></textarea></div>
          <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">{editId ? 'Update' : 'Create'} Item</button>
        </form>
      </Modal>
    </div>);};
export default ItemMaster;
