import { useState, useEffect } from 'react';import { useParams } from 'react-router-dom';import api from '../../services/api';import toast from 'react-hot-toast';

const InvoicePDF = () => { const { id } = useParams(); const [data, setData] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => { const fetch = async () => { try { const { data } = await api.get(`/invoices/${id}/pdf-data`); setData(data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, [id]);
  const handlePrint = () => window.print();
  if (loading) return <div className="flex justify-center py-20"><div className="animate-spin rounded-full h-12 w-12 border-t-2 border-emerald-500"></div></div>;
  if (!data) return <p className="text-center text-gray-400 py-20">Invoice not found</p>;
  const { invoice, companyInfo } = data;
  return (<div className="max-w-4xl mx-auto"><div className="flex justify-end mb-4 print:hidden"><button onClick={handlePrint} className="px-4 py-2 bg-emerald-600 text-white rounded-xl font-medium hover:bg-emerald-700">🖨️ Print / Save PDF</button></div>
    <div className="bg-white text-gray-900 rounded-2xl p-8 print:p-4 print:shadow-none shadow-xl">
      {/* Header */}
      <div className="flex justify-between items-start mb-8 border-b pb-6"><div><h1 className="text-2xl font-bold text-emerald-600">LexaERP</h1><p className="text-sm text-gray-600">{companyInfo.name}</p><p className="text-xs text-gray-500">{companyInfo.address}</p><p className="text-xs text-gray-500">{companyInfo.email} | {companyInfo.phone}</p><p className="text-xs text-gray-500">GST: {companyInfo.gst}</p></div><div className="text-right"><h2 className="text-xl font-bold text-gray-800">TAX INVOICE</h2><p className="text-sm text-gray-600 mt-1">Invoice #: <span className="font-semibold">{invoice.invoiceNumber}</span></p><p className="text-sm text-gray-600">Date: {new Date(invoice.invoiceDate).toLocaleDateString('en-IN')}</p>{invoice.dueDate && <p className="text-sm text-gray-600">Due: {new Date(invoice.dueDate).toLocaleDateString('en-IN')}</p>}</div></div>
      {/* Bill To */}
      {invoice.client && (<div className="mb-8"><h3 className="text-sm font-semibold text-gray-500 uppercase mb-2">Bill To</h3><p className="font-semibold text-gray-800">{invoice.client.name}</p><p className="text-sm text-gray-600">{invoice.client.company}</p>{invoice.client.address && <p className="text-sm text-gray-600">{invoice.client.address}</p>}{invoice.client.gst && <p className="text-sm text-gray-600">GST: {invoice.client.gst}</p>}</div>)}
      {/* Items Table */}
      <table className="w-full text-sm mb-8"><thead><tr className="bg-gray-100"><th className="text-left px-4 py-3 font-semibold">#</th><th className="text-left px-4 py-3 font-semibold">Description</th><th className="text-center px-4 py-3 font-semibold">HSN</th><th className="text-center px-4 py-3 font-semibold">Qty</th><th className="text-right px-4 py-3 font-semibold">Rate</th><th className="text-right px-4 py-3 font-semibold">Tax</th><th className="text-right px-4 py-3 font-semibold">Amount</th></tr></thead>
        <tbody>{(invoice.items || []).map((item, idx) => (<tr key={idx} className="border-b"><td className="px-4 py-3">{idx+1}</td><td className="px-4 py-3">{item.description}</td><td className="text-center px-4 py-3">{item.hsnCode || '—'}</td><td className="text-center px-4 py-3">{item.quantity} {item.unit}</td><td className="text-right px-4 py-3">₹{(item.rate||0).toLocaleString('en-IN')}</td><td className="text-right px-4 py-3">{item.taxPercent}%</td><td className="text-right px-4 py-3 font-medium">₹{(item.totalAmount||item.amount||0).toLocaleString('en-IN')}</td></tr>))}</tbody></table>
      {/* Totals */}
      <div className="flex justify-end"><div className="w-72 space-y-2 text-sm"><div className="flex justify-between"><span className="text-gray-600">Subtotal</span><span>₹{(invoice.subtotal||0).toLocaleString('en-IN')}</span></div>{invoice.cgst > 0 && <div className="flex justify-between"><span className="text-gray-600">CGST</span><span>₹{invoice.cgst.toLocaleString('en-IN')}</span></div>}{invoice.sgst > 0 && <div className="flex justify-between"><span className="text-gray-600">SGST</span><span>₹{invoice.sgst.toLocaleString('en-IN')}</span></div>}{invoice.igst > 0 && <div className="flex justify-between"><span className="text-gray-600">IGST</span><span>₹{invoice.igst.toLocaleString('en-IN')}</span></div>}<div className="flex justify-between"><span className="text-gray-600">Total Tax</span><span>₹{(invoice.totalTax||0).toLocaleString('en-IN')}</span></div><div className="flex justify-between font-bold text-lg border-t pt-2"><span>Grand Total</span><span className="text-emerald-600">₹{(invoice.grandTotal||0).toLocaleString('en-IN')}</span></div>{invoice.amountInWords && <p className="text-xs text-gray-500 italic">{invoice.amountInWords}</p>}</div></div>
      {/* Footer */}
      <div className="mt-8 border-t pt-6 text-xs text-gray-500"><div className="grid grid-cols-2 gap-8"><div>{invoice.paymentTerms && <p><strong>Payment Terms:</strong> {invoice.paymentTerms}</p>}{invoice.bankDetails?.bankName && (<div className="mt-2"><p className="font-semibold text-gray-600">Bank Details:</p><p>{invoice.bankDetails.bankName} | A/c: {invoice.bankDetails.accountNo}</p><p>IFSC: {invoice.bankDetails.ifsc} | Branch: {invoice.bankDetails.branch}</p></div>)}</div><div className="text-right"><p className="mb-8">Authorized Signatory</p><p className="border-t border-gray-300 inline-block px-8 pt-1">{companyInfo.name}</p></div></div></div></div></div>);};
export default InvoicePDF;
