import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiFileText, FiDollarSign, FiEdit2, FiTrash2 } from 'react-icons/fi';import { useNavigate } from 'react-router-dom';import Modal from '../../components/Modals/Modal';
const Invoices = () => { const [invoices, setInvoices] = useState([]);  const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [filter, setFilter] = useState(''); const navigate = useNavigate();
  const [form, setForm] = useState({ invoiceType: 'sales', client: '', billingAddress: '', items: [{ description: '', quantity: 1, rate: 0, amount: 0, taxPercent: 18 }], subtotal: 0, totalTax: 0, grandTotal: 0, paymentTerms: 'Net 30', dueDate: '' });
  useEffect(() => { const fetch = async () => { try { const params = filter ? { paymentStatus: filter } : {}; const { data } = await api.get('/invoices', { params }); setInvoices(data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, [filter]);
  const addLineItem = () => setForm({ ...form, items: [...form.items, { description: '', quantity: 1, rate: 0, amount: 0, taxPercent: 18 }] });
  const updateLineItem = (idx, field, val) => { const items = [...form.items]; items[idx][field] = val; items[idx].amount = items[idx].quantity * items[idx].rate; items[idx].taxAmount = items[idx].amount * (items[idx].taxPercent / 100); items[idx].totalAmount = items[idx].amount + items[idx].taxAmount; const subtotal = items.reduce((s, i) => s + i.amount, 0); const totalTax = items.reduce((s, i) => s + (i.taxAmount || 0), 0); setForm({ ...form, items, subtotal, totalTax, grandTotal: subtotal + totalTax }); };
  const handleSubmit = async (e) => { e.preventDefault(); try { await api.post('/invoices', form); toast.success('Invoice Created'); setShowModal(false); const { data } = await api.get('/invoices'); setInvoices(data); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  const handlePayment = async (id) => { const amount = prompt('Enter payment amount:'); if (!amount) return; try { await api.post(`/invoices/${id}/payment`, { date: new Date(), amount: Number(amount), method: 'bank_transfer' }); toast.success('Payment recorded'); const { data } = await api.get('/invoices'); setInvoices(data); } catch { toast.error('Failed'); } };
  const PAYMENT_COLORS = { unpaid: 'bg-red-900/40 text-red-400', partially_paid: 'bg-amber-900/40 text-amber-400', paid: 'bg-emerald-900/40 text-emerald-400', overdue: 'bg-red-900/60 text-red-300' };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Invoices</h1><p className="text-sm text-gray-400">Sales & purchase invoices with GST</p></div><button onClick={()=>{setForm({invoiceType:'sales',client:'',billingAddress:'',items:[{description:'',quantity:1,rate:0,amount:0,taxPercent:18}],subtotal:0,totalTax:0,grandTotal:0,paymentTerms:'Net 30',dueDate:''});setShowModal(true);}} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus />New Invoice</button></div>
    <div className="flex flex-wrap gap-2">{['','unpaid','partially_paid','paid','overdue'].map(s=>(<button key={s} onClick={()=>setFilter(s)} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${filter===s?'bg-emerald-600 text-white':'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}>{s?s.replace(/_/g,' '):'All'}</button>))}</div>
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-6 py-4 text-gray-400">Invoice #</th><th className="text-left px-6 py-4 text-gray-400">Client / Vendor</th><th className="text-left px-6 py-4 text-gray-400">Type</th><th className="text-left px-6 py-4 text-gray-400">Amount</th><th className="text-left px-6 py-4 text-gray-400">Paid</th><th className="text-left px-6 py-4 text-gray-400">Balance</th><th className="text-left px-6 py-4 text-gray-400">Status</th><th className="text-left px-6 py-4 text-gray-400">Actions</th></tr></thead>
      <tbody>{loading ? <tr><td colSpan="8" className="px-6 py-12 text-center text-gray-500">Loading...</td></tr> : invoices.map(inv=>(<tr key={inv._id} className="border-b border-gray-700/30 hover:bg-gray-800/60"><td className="px-6 py-4 text-emerald-400 font-mono text-xs">{inv.invoiceNumber}</td><td className="px-6 py-4 text-white">{inv.client?.name || inv.vendor?.name || '—'}</td><td className="px-6 py-4"><span className="px-2 py-0.5 bg-gray-700 text-gray-300 rounded-full text-xs">{inv.invoiceType}</span></td><td className="px-6 py-4 text-white font-semibold">₹{(inv.grandTotal||0).toLocaleString('en-IN')}</td><td className="px-6 py-4 text-emerald-400">₹{(inv.paidAmount||0).toLocaleString('en-IN')}</td><td className="px-6 py-4 text-red-400">₹{(inv.balanceDue||0).toLocaleString('en-IN')}</td><td className="px-6 py-4"><span className={`px-2.5 py-1 rounded-full text-xs font-medium ${PAYMENT_COLORS[inv.paymentStatus]}`}>{inv.paymentStatus?.replace(/_/g,' ')}</span></td>
        <td className="px-6 py-4 flex gap-2">{inv.paymentStatus!=='paid' && <button onClick={()=>handlePayment(inv._id)} className="px-2 py-1 bg-emerald-600/20 text-emerald-400 rounded-lg text-xs hover:bg-emerald-600/30"><FiDollarSign className="inline mr-1" size={12}/>Pay</button>}<button onClick={()=>navigate(`/invoices/${inv._id}/pdf`)} className="px-2 py-1 bg-blue-600/20 text-blue-400 rounded-lg text-xs hover:bg-blue-600/30"><FiFileText className="inline mr-1" size={12}/>PDF</button></td></tr>))}</tbody></table></div></div>
    <Modal isOpen={showModal} onClose={()=>setShowModal(false)} title="New Invoice"><form onSubmit={handleSubmit} className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Invoice Type</label><select value={form.invoiceType} onChange={e=>setForm({...form,invoiceType:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="sales">Sales</option><option value="proforma">Proforma</option></select></div><div><label className="block text-sm text-gray-400 mb-1">Due Date</label><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div></div>
      <div><label className="block text-sm text-gray-400 mb-2">Line Items</label>{form.items.map((li,idx)=>(<div key={idx} className="grid grid-cols-5 gap-2 mb-2"><input value={li.description} onChange={e=>updateLineItem(idx,'description',e.target.value)} placeholder="Description" className="col-span-2 bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm"/><input type="number" value={li.quantity} onChange={e=>updateLineItem(idx,'quantity',Number(e.target.value))} placeholder="Qty" className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm"/><input type="number" value={li.rate} onChange={e=>updateLineItem(idx,'rate',Number(e.target.value))} placeholder="Rate" className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm"/><span className="text-emerald-400 text-sm self-center">₹{(li.amount||0).toLocaleString('en-IN')}</span></div>))}<button type="button" onClick={addLineItem} className="text-emerald-400 text-sm"><FiPlus className="inline mr-1" size={12}/>Add Line</button></div>
      <div className="border-t border-gray-700 pt-3 text-sm space-y-1"><div className="flex justify-between"><span className="text-gray-400">Subtotal</span><span className="text-white">₹{form.subtotal.toLocaleString('en-IN')}</span></div><div className="flex justify-between"><span className="text-gray-400">Tax (GST)</span><span className="text-white">₹{form.totalTax.toLocaleString('en-IN')}</span></div><div className="flex justify-between font-bold"><span className="text-white">Grand Total</span><span className="text-emerald-400">₹{form.grandTotal.toLocaleString('en-IN')}</span></div></div>
      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">Create Invoice</button></form></Modal></div>);};
export default Invoices;
