import { useState, useEffect } from 'react';import { useParams, useNavigate } from 'react-router-dom';import api from '../../services/api';import toast from 'react-hot-toast';import { FiArrowLeft, FiPlay, FiCheckCircle, FiPackage } from 'react-icons/fi';
const WorkOrderDetail = () => { const { id } = useParams(); const navigate = useNavigate(); const [wo, setWo] = useState(null); const [loading, setLoading] = useState(true);
  const fetch = async () => { try { const { data } = await api.get(`/work-orders/${id}`); setWo(data); } catch { toast.error('Failed'); } finally { setLoading(false); } };
  useEffect(() => { fetch(); }, [id]);
  const handleTaskAction = async (taskIndex, status) => { try { await api.put(`/work-orders/${id}/task-status`, { taskIndex, status }); toast.success(status === 'in_progress' ? 'Task started' : 'Task completed'); fetch(); } catch { toast.error('Failed'); } };
  const handleIssueMaterial = async (materialIndex) => { const mat = wo.materials[materialIndex]; const qty = mat.requiredQty - (mat.issuedQty || 0); if (qty <= 0) return toast.error('Already fully issued'); try { await api.put(`/work-orders/${id}/issue-material`, { materialIndex, issuedQty: qty }); toast.success('Material issued from inventory'); fetch(); } catch { toast.error('Failed — check stock levels'); } };
  if (loading) return <div className="flex justify-center py-20"><div className="animate-spin rounded-full h-12 w-12 border-t-2 border-emerald-500"></div></div>;
  if (!wo) return <p className="text-gray-400 text-center py-20">Not found</p>;
  return (<div className="space-y-6">
    <div className="flex items-center gap-4"><button onClick={()=>navigate('/work-orders')} className="p-2 rounded-lg hover:bg-gray-800 text-gray-400"><FiArrowLeft/></button><div><h1 className="text-2xl font-bold text-white">{wo.woNumber}</h1><p className="text-sm text-gray-400">{wo.productName} — SO: {wo.saleOrder?.soNumber}</p></div><span className={`ml-auto px-3 py-1 rounded-full text-xs font-medium ${wo.status==='completed'?'bg-emerald-900/40 text-emerald-400':'bg-amber-900/40 text-amber-400'}`}>{wo.status?.replace(/_/g,' ')}</span></div>
    {/* Progress */}
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6"><div className="flex justify-between mb-2"><span className="text-gray-400 text-sm">Overall Progress</span><span className="text-white font-bold text-xl">{wo.progressPercent}%</span></div><div className="w-full bg-gray-700 rounded-full h-4"><div className="bg-gradient-to-r from-emerald-500 to-emerald-400 h-4 rounded-full transition-all duration-500" style={{width:`${wo.progressPercent}%`}}></div></div></div>
    {/* Tasks */}
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6"><h3 className="text-lg font-semibold text-white mb-4">Tasks / Operations</h3><div className="space-y-3">{(wo.tasks || []).map((task, idx) => (<div key={idx} className={`flex items-center gap-4 p-4 rounded-xl ${task.status==='completed'?'bg-emerald-900/20 border border-emerald-700/30':task.status==='in_progress'?'bg-blue-900/20 border border-blue-700/30':'bg-gray-900/40 border border-gray-700/30'}`}>
      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${task.status==='completed'?'bg-emerald-600 text-white':task.status==='in_progress'?'bg-blue-600 text-white':'bg-gray-700 text-gray-400'}`}>{task.sequence}</div>
      <div className="flex-1"><p className={`font-medium ${task.status==='completed'?'text-emerald-400':task.status==='in_progress'?'text-blue-400':'text-white'}`}>{task.taskName}</p><p className="text-xs text-gray-400">{task.assignedTo?.name || 'Unassigned'} • Est: {task.estimatedHours}h {task.actualHours > 0 ? `• Actual: ${task.actualHours}h` : ''}</p></div>
      <div>{task.status==='pending' && <button onClick={()=>handleTaskAction(idx,'in_progress')} className="flex items-center gap-1 px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-medium"><FiPlay size={12}/>Start</button>}
        {task.status==='in_progress' && <button onClick={()=>handleTaskAction(idx,'completed')} className="flex items-center gap-1 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-xs font-medium"><FiCheckCircle size={12}/>Done</button>}
        {task.status==='completed' && <span className="text-emerald-400 text-sm">✓ Done</span>}</div></div>))}</div></div>
    {/* Materials */}
    {wo.materials?.length > 0 && (<div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6"><h3 className="text-lg font-semibold text-white mb-4">Material Consumption</h3><table className="w-full text-sm"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-4 py-3 text-gray-400">Material</th><th className="text-left px-4 py-3 text-gray-400">Required</th><th className="text-left px-4 py-3 text-gray-400">Issued</th><th className="text-left px-4 py-3 text-gray-400">Action</th></tr></thead>
      <tbody>{wo.materials.map((mat, idx) => (<tr key={idx} className="border-b border-gray-700/30"><td className="px-4 py-3 text-white">{mat.item?.name}</td><td className="px-4 py-3 text-gray-300">{mat.requiredQty} {mat.unit}</td><td className="px-4 py-3 text-emerald-400">{mat.issuedQty || 0}</td><td className="px-4 py-3">{(mat.issuedQty || 0) < mat.requiredQty && <button onClick={()=>handleIssueMaterial(idx)} className="px-2 py-1 bg-blue-600/20 text-blue-400 rounded text-xs hover:bg-blue-600/30"><FiPackage className="inline mr-1" size={12}/>Issue</button>}</td></tr>))}</tbody></table></div>)}</div>);};
export default WorkOrderDetail;
