import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiEye, FiTrash2 } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const WorkOrders = () => { const [workOrders, setWorkOrders] = useState([]); const [saleOrders, setSaleOrders] = useState([]); const [boms, setBoms] = useState([]); const [operators, setOperators] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [filter, setFilter] = useState(''); const navigate = useNavigate();
  const [form, setForm] = useState({ saleOrder: '', bom: '', productName: '', quantity: 1, plannedStartDate: '', plannedEndDate: '', priority: 'medium', tasks: [{ sequence: 1, taskName: '', estimatedHours: 0, assignedTo: '' }] });
  useEffect(() => { const fetchLocal = async () => { try { const params = filter ? { status: filter } : {}; const [w, s, b, u] = await Promise.all([api.get('/work-orders', { params }), api.get('/sale-orders'), api.get('/bom'), api.get('/users')]); setWorkOrders(w.data); setSaleOrders(s.data); setBoms(b.data.filter(bm => bm.status === 'approved')); setOperators(u.data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetchLocal(); }, [filter]);
  const addTask = () => setForm({ ...form, tasks: [...form.tasks, { sequence: form.tasks.length + 1, taskName: '', estimatedHours: 0, assignedTo: '' }] });
  const updateTask = (idx, field, val) => { const tasks = [...form.tasks]; tasks[idx][field] = val; setForm({ ...form, tasks }); };
  const handleSubmit = async (e) => { 
    e.preventDefault(); 
    try { 
      const payload = { ...form };
      payload.tasks = payload.tasks.map(t => (!t.assignedTo ? { ...t, assignedTo: undefined } : t));
      await api.post('/work-orders', payload); 
      toast.success('Work Order Created'); 
      setShowModal(false); 
      const { data } = await api.get('/work-orders'); 
      setWorkOrders(data); 
    } catch (err) { toast.error(err.response?.data?.message || 'Error'); } 
  };
  const STATUS_COLORS = { planned: 'bg-blue-900/40 text-blue-400', material_issued: 'bg-indigo-900/40 text-indigo-400', in_progress: 'bg-amber-900/40 text-amber-400', on_hold: 'bg-gray-700 text-gray-400', completed: 'bg-emerald-900/40 text-emerald-400', cancelled: 'bg-red-900/40 text-red-400' };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Work Orders</h1><p className="text-sm text-gray-400">Step 7: Production & Manufacturing</p></div><button onClick={()=>{setForm({saleOrder:'',bom:'',productName:'',quantity:1,plannedStartDate:'',plannedEndDate:'',priority:'medium',tasks:[{sequence:1,taskName:'',estimatedHours:0,assignedTo:''}]});setShowModal(true);}} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus />New Work Order</button></div>
    <div className="flex flex-wrap gap-2">{['','planned','material_issued','in_progress','on_hold','completed'].map(s=>(<button key={s} onClick={()=>setFilter(s)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${filter===s?'bg-emerald-600 text-white':'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}>{s?s.replace(/_/g,' '):'All'}</button>))}</div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{loading ? <p className="text-gray-500 col-span-3 text-center py-12">Loading...</p> : workOrders.length === 0 ? <p className="text-gray-500 col-span-3 text-center py-12">No work orders</p> : workOrders.map(wo=>(<div key={wo._id} className="bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5 hover:border-gray-600/50 transition-all cursor-pointer" onClick={()=>navigate(`/work-orders/${wo._id}`)}>
      <div className="flex justify-between items-start mb-3"><div><p className="text-emerald-400 font-mono text-xs">{wo.woNumber}</p><h3 className="text-white font-semibold mt-1">{wo.productName}</h3><p className="text-xs text-gray-400">SO: {wo.saleOrder?.soNumber || '—'}</p></div><div className="flex flex-col items-end gap-1"><span className={`px-2.5 py-1 rounded-full text-xs font-medium ${STATUS_COLORS[wo.status]}`}>{wo.status?.replace(/_/g,' ')}</span><span className={`text-xs ${wo.priority==='urgent'?'text-red-400':wo.priority==='high'?'text-orange-400':'text-gray-400'}`}>{wo.priority}</span></div></div>
      <div className="w-full bg-gray-700 rounded-full h-2.5 mb-1"><div className="bg-emerald-500 h-2.5 rounded-full transition-all duration-500" style={{width:`${wo.progressPercent}%`}}></div></div>
      <div className="flex justify-between text-xs text-gray-400 mt-1"><span>{wo.progressPercent}% complete</span><span>Qty: {wo.quantity}</span></div></div>))}</div>
    <Modal isOpen={showModal} onClose={()=>setShowModal(false)} title="New Work Order"><form onSubmit={handleSubmit} className="space-y-4">
      <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Sale Order *</label><select required value={form.saleOrder} onChange={e=>setForm({...form,saleOrder:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="">Select...</option>{saleOrders.filter(s=>['confirmed','bom_ready','in_production'].includes(s.status)).map(s=><option key={s._id} value={s._id}>{s.soNumber} — {s.subject}</option>)}</select></div><div><label className="block text-sm text-gray-400 mb-1">BOM *</label><select required value={form.bom} onChange={e=>setForm({...form,bom:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="">Select...</option>{boms.map(b=><option key={b._id} value={b._id}>{b.bomNumber} — {b.productName}</option>)}</select></div></div>
      <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Product Name *</label><input required value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Priority</label><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></div></div>
      <div><label className="block text-sm text-gray-400 mb-2">Tasks / Operations</label>{form.tasks.map((t,idx)=>(<div key={idx} className="flex flex-wrap sm:flex-nowrap gap-2 mb-2"><span className="text-gray-500 text-sm mt-2.5 w-6">{t.sequence}.</span><input value={t.taskName} onChange={e=>updateTask(idx,'taskName',e.target.value)} placeholder="Task name" className="flex-1 min-w-[120px] bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:border-emerald-500 focus:outline-none"/><input type="number" value={t.estimatedHours} onChange={e=>updateTask(idx,'estimatedHours',Number(e.target.value))} placeholder="Hours" className="w-20 bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm"/><select value={t.assignedTo} onChange={e=>updateTask(idx,'assignedTo',e.target.value)} className="w-32 sm:w-40 bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none"><option value="">Unassigned</option>{operators.map(op=><option key={op._id} value={op._id}>{op.name}</option>)}</select></div>))}<button type="button" onClick={addTask} className="text-emerald-400 text-sm"><FiPlus className="inline mr-1" size={12}/>Add Task</button></div>
      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">Create Work Order</button></form></Modal></div>);};
export default WorkOrders;
