import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiBox, FiAlertTriangle, FiSearch } from 'react-icons/fi';
const StockLevels = () => { const [levels, setLevels] = useState([]); const [alerts, setAlerts] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState('');
  useEffect(() => { const fetch = async () => { try { const [l, a] = await Promise.all([api.get('/inventory/levels'), api.get('/inventory/alerts')]); setLevels(l.data); setAlerts(a.data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, []);
  const filtered = levels.filter(l => !search || l.item?.name?.toLowerCase().includes(search.toLowerCase()) || l.item?.itemCode?.toLowerCase().includes(search.toLowerCase()));
  return (<div className="space-y-6"><div><h1 className="text-2xl font-bold text-white">Inventory / Stock Levels</h1><p className="text-sm text-gray-400">Real-time inventory overview</p></div>
    {alerts.length > 0 && (<div className="bg-red-900/20 border border-red-700/50 rounded-2xl p-4"><h3 className="text-sm font-semibold text-red-400 flex items-center gap-2 mb-2"><FiAlertTriangle /> Low Stock Alerts ({alerts.length})</h3><div className="flex flex-wrap gap-2">{alerts.map((a,i) => (<span key={i} className="px-3 py-1 bg-red-900/30 text-red-300 rounded-full text-xs">{a.item?.name}: {a.currentQuantity} left (ROL: {a.item?.reorderLevel})</span>))}</div></div>)}
    <div className="relative"><FiSearch className="absolute left-4 top-3 text-gray-400" /><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search items..." className="w-full bg-gray-800/50 border border-gray-700/50 rounded-xl pl-10 pr-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none" /></div>
    <div className="bg-gray-800/50 border border-gray-700/50 rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700/50"><th className="text-left px-6 py-4 text-gray-400">Code</th><th className="text-left px-6 py-4 text-gray-400">Item</th><th className="text-left px-6 py-4 text-gray-400">Type</th><th className="text-left px-6 py-4 text-gray-400">Current Qty</th><th className="text-left px-6 py-4 text-gray-400">Reserved</th><th className="text-left px-6 py-4 text-gray-400">Available</th><th className="text-left px-6 py-4 text-gray-400">Warehouse</th></tr></thead>
      <tbody>{loading ? <tr><td colSpan="7" className="px-6 py-12 text-center text-gray-500">Loading...</td></tr> : filtered.length === 0 ? <tr><td colSpan="7" className="px-6 py-12 text-center text-gray-500">No stock data</td></tr> : filtered.map((l,i)=>(<tr key={i} className="border-b border-gray-700/30 hover:bg-gray-800/60"><td className="px-6 py-4 text-emerald-400 font-mono text-xs">{l.item?.itemCode}</td><td className="px-6 py-4 text-white">{l.item?.name}</td><td className="px-6 py-4"><span className="px-2 py-0.5 bg-gray-700 text-gray-300 rounded-full text-xs">{l.item?.type?.replace(/_/g,' ')}</span></td><td className={`px-6 py-4 font-semibold ${l.currentQuantity <= (l.item?.reorderLevel || 0) ? 'text-red-400' : 'text-white'}`}>{l.currentQuantity} {l.item?.unit}</td><td className="px-6 py-4 text-amber-400">{l.reservedQuantity}</td><td className="px-6 py-4 text-emerald-400 font-semibold">{l.availableQuantity}</td><td className="px-6 py-4 text-gray-400">{l.warehouse?.name || 'Default'}</td></tr>))}</tbody></table></div></div></div>);};
export default StockLevels;
