import { useState, useEffect } from 'react';import api from '../../services/api';import toast from 'react-hot-toast';import { FiPlus, FiEdit2, FiTrash2, FiMapPin } from 'react-icons/fi';import Modal from '../../components/Modals/Modal';
const Warehouses = () => { const [warehouses, setWarehouses] = useState([]); const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [editId, setEditId] = useState(null);
  const [form, setForm] = useState({ name: '', code: '', address: '', type: 'raw_material_store' });
  useEffect(() => { const fetch = async () => { try { const { data } = await api.get('/inventory/warehouses'); setWarehouses(data); } catch { toast.error('Failed'); } finally { setLoading(false); } }; fetch(); }, []);
  const handleSubmit = async (e) => { e.preventDefault(); try { if (editId) { await api.put(`/inventory/warehouses/${editId}`, form); toast.success('Updated'); } else { await api.post('/inventory/warehouses', form); toast.success('Created'); } setShowModal(false); setEditId(null); const { data } = await api.get('/inventory/warehouses'); setWarehouses(data); } catch (err) { toast.error(err.response?.data?.message || 'Error'); } };
  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Warehouses</h1><p className="text-sm text-gray-400">Storage locations management</p></div><button onClick={()=>{setEditId(null);setForm({name:'',code:'',address:'',type:'raw_material_store'});setShowModal(true);}} className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-xl font-medium"><FiPlus />New Warehouse</button></div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{loading ? <p className="text-gray-500 col-span-3 text-center py-12">Loading...</p> : warehouses.map(w=>(<div key={w._id} className="bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5 hover:border-gray-600/50 transition-all"><div className="flex items-center gap-3 mb-3"><FiMapPin className="text-emerald-400 text-xl" /><div><h3 className="text-white font-semibold">{w.name}</h3><p className="text-xs text-gray-400 font-mono">{w.code}</p></div></div><p className="text-sm text-gray-400 mb-3">{w.address || '—'}</p><span className="px-2 py-0.5 bg-gray-700 text-gray-300 rounded-full text-xs">{w.type?.replace(/_/g,' ')}</span><div className="flex gap-2 mt-3 justify-end"><button onClick={()=>{setForm({name:w.name,code:w.code,address:w.address||'',type:w.type});setEditId(w._id);setShowModal(true);}} className="p-1.5 rounded-lg hover:bg-gray-700 text-gray-400"><FiEdit2 size={14}/></button></div></div>))}</div>
    <Modal isOpen={showModal} onClose={()=>setShowModal(false)} title={editId?'Edit Warehouse':'New Warehouse'}><form onSubmit={handleSubmit} className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-400 mb-1">Name *</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><div><label className="block text-sm text-gray-400 mb-1">Code *</label><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div></div><div><label className="block text-sm text-gray-400 mb-1">Type</label><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"><option value="raw_material_store">Raw Material Store</option><option value="finished_goods">Finished Goods</option><option value="wip">Work In Progress</option><option value="general">General</option></select></div><div><label className="block text-sm text-gray-400 mb-1">Address</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-2.5 text-white focus:border-emerald-500 focus:outline-none"/></div><button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-2.5 rounded-xl font-medium">{editId?'Update':'Create'}</button></form></Modal></div>);};
export default Warehouses;
